### PR TITLE
Add TheQuestForTruth

### PR DESCRIPTION
**Pull request by GuillaumeElias**
I added a little platformer that I made.

### CODE REVIEW

**Comment by eried** [comment]
Thanks! I'll merge it tomorrow

**Comment by GuillaumeElias** [comment]
Many thanks !

How long does it take for it to appear on https://arduboy.ried.cl/ ?

Happy holidays !

--Guillaume--

Le ven. 27 déc. 2019 à 11:55, Erwin Ried <notifications@github.com> a
écrit :

**Comment by eried** [comment]
🤩 it's now up

**Comment by GuillaumeElias** [comment]
Awesome ! Thanks !

--Guillaume--

Le ven. 27 déc. 2019 à 14:48, Erwin Ried <notifications@github.com> a
écrit :

**Pull request merged**
