### PR TITLE
Twotris

### PR DESCRIPTION
**Pull request by skaterced**
Hi,
I finished this game a few weeks ago but coulnd't test it with someone else because of the COVID-19
Here it is anyway. I'm already a long way in the next one so I don't feel like changing things in Twotris now.
Thank you for your repo.
Keep safe
Cédric

By the way, I made a mess uploading files in the wrong place, but I think it's cleared now.

### CODE REVIEW

**Comment by eried** [comment]
Thanks! Game source code is not actually stored in this repo, could you remove that? Ideally it will be only 4 or 5 files in the commit

**Review by eried — CHANGES_REQUESTED** [review]
Please remove source code and internal photos, only leave 1 png for the game banner picture

**Comment by skaterced** [comment]
Hi,

Can I reply here or do I have to do it in Github ?
[ok first question answered]
image

Ok, I removed the code and added source.url

I had only one picture on the folder: screen.png (an in-game screenshot)
Should it be the title ? ->

[cid:30370606-79ff-4732-bce3-f49215dde3e1]

Do I need to click on pull request again ?

Thank you for your help

See you
Ced
________________________________
De : Erwin Ried <notifications@github.com>
Envoyé : mardi, 14 avril 2020 13:13
À : eried/ArduboyCollection <ArduboyCollection@noreply.github.com>
Cc : skaterced <skaterced@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [eried/ArduboyCollection] Twotris (#133)


@eried requested changes on this pull request.

Please remove source code and internal photos, only leave 1 png for the game banner picture

**Comment by eried** [comment]
Yes, what it would be easier is that you save your 5 files and delete your fork and then create new fork and upload those 5 files. 

I know it might be confusing but ideally you would have git installed on your machine and it would make sense (using the web interface is a bit cumbersome). If you struggle too much, I could add your game from your files (there is still 12 files in this Pull request, some of which you should remove) but first, try yourself.

**Comment by skaterced** [comment]
You want me to delete the whole "ArduboyCollection" fork right? How do I do that?

**Comment by eried** [comment]
Settings / Delete.

Then you fork the same again, add only 5 files and Pull request. That is all

**Pull request closed without merging**
