### PR TITLE
Ardu-Racer - Initial Add to Repo

### PR DESCRIPTION
**Pull request by tonym128**
Hi, I finished my game it's up at 
https://github.com/tonym128/ArduRacer
and community post with instructions at 
https://community.arduboy.com/t/arduracer-a-trackmania-type-time-trial-game/8850

Thanks for this awesome collection and list.

### CODE REVIEW

**Comment by eried** [comment]
Nice! Thanks!

**Comment by eried** [comment]
PS: Didn't knew firefox added those extras in the URL, it is parsed as an ini file so it wont affect, but thanks for the care :D

**Comment by tonym128** [comment]
Update sorry, seems there's something wrong with my hex... I will update now.

Just checked, so cool to have it in a collection with other games, not sure how the %2F snuck in, but while the image works with it, the emulator doesn't :'(

Sorry not sure if it's something I did or not...

 								<a class="image fit"></a> 

 									<a href="arduboy:https://raw.githubusercontent.com/eried/ArduboyCollection/master/Racing%2FArdu-Racer%2FArduRacer.hex" class="button style2 fit customprotocol">Upload to my Arduboy <i class="fa fa-magic" aria-hidden="true"></i></a>

**Comment by eried** [comment]
For me works on both :)

**Comment by tonym128** [comment]
> 
> 
> For me works on both :)

Phew! okay that's great 👍 
Bit panicy with my first published game 😄

**Comment by eried** [comment]
hahah! I think that is just the encoding of the path, not sure why it is only in that section, I will take a look later https://github.com/eried/ArduboyCollection/issues/140

**Pull request merged**
